
-- Define product aggregate function (not optimized for windows usage)




CREATE OR REPLACE FUNCTION  MULTIPLY(BIGINT, BIGINT) RETURNS BIGINT
    AS 'select $1 * $2;'
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;
	
	
CREATE OR REPLACE AGGREGATE PRODUCT  EXISTS (BIGINT)
(
    sfunc = MULTIPLY,
    stype = BIGINT,
    initcond = '1'
);


--  Define unique array intersection aggregate


CREATE OR REPLACE FUNCTION ARRAY_UNIQUE_INTERSECT(a ANYARRAY, b ANYARRAY) RETURNS ANYARRAY
	AS 'WITH cte(element) AS 
	(
		SELECT UNNEST(a)  
		INTERSECT
		SELECT  UNNEST(b) 
		)
	SELECT ARRAY_AGG(element) FROM cte;'
	LANGUAGE SQL
	IMMUTABLE
	RETURNS NULL ON NULL INPUT; 
	
	
CREATE OR REPLACE AGGREGATE ARRAY_UNIQUE_INTERSECT_AGG (ANYARRAY)
(
    sfunc = ARRAY_UNIQUE_INTERSECT,
    stype = ANYARRAY
);


-- Function reversing an array

CREATE OR REPLACE FUNCTION ARRAY_REVERSE(a ANYARRAY) RETURNS ANYARRAY
	AS 'WITH cte(element, pos) AS 
	(
		SELECT * 
		FROM 
        	UNNEST(a) WITH ORDINALITY AS t(element, pos) 
		
	)
		
		
	SELECT ARRAY_AGG(element ORDER BY pos DESC) FROM cte;'
	LANGUAGE sql
	IMMUTABLE
	RETURNS NULL ON NULL INPUT; 


